server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: ../certificate/doto.p12
    key-store-password: DoTo
    key-alias: DoTo
security:
  require-ssl: true
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@domain
    password: password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/DoTo_dev
    username: DoTo
    password: DoTo
config:
  security:
    jwt:
      secret: DoTo-SecretKey
      expiration-time: 6_000_000
      refresh-after: 600_000
  password-reset:
    characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
    length: 6
  task:
    default_state: todo